### ISSUE TITLE
Bundle size benchmarks

### ISSUE THREAD

**Issue by n1ru4l** [kitten/graphql-web-lite#4]
It would be great to have a comparison of the bundle size of importing the functions from graphql and graphql-web-lite in order to have a better understanding of the significance of this package. I guess generating this could be automated via a Github action.

**Comment by JoviDeCroock** [comment]
On every PR you can see a difference between an urql build with lite and graphql https://github.com/kitten/graphql-web-lite/pull/3#issuecomment-909499438

**Comment by n1ru4l** [comment]
Oh, that is awesome! Thank you!
